### ISSUE TITLE
Add a way to specify the directory entry

### ISSUE THREAD

**Issue by alexherbo2** [topisani/sidetree#20]
It could be nice to have a variable pointing to the current directory entry, such as `sidetree_directory_entry`.

The motivation is to avoid logic in mappings, when we want to select the directory entry.

**Comment by topisani** [comment]
when you say directory entry, you are referring to the parent directory if the current entry is a file, and the current entry if it is a dir, right? if so, that seems like a good idea

**Comment by alexherbo2** [comment]
Yep

**Comment by topisani** [comment]
done!
